export const en = {
  language: "中文 / EN",
  nav: [{ label: "About", href: "#about" }, { label: "Now", href: "#now" }, { label: "Projects", href: "#projects" }, { label: "Notes", href: "#notes" }, { label: "Life", href: "#life" }, { label: "Career", href: "/en/work" }],
  welcome: { eyebrow: "JOEY LUO · PERSONAL SPACE", title: ["Welcome to", "My Personal Space"], line: "Explore · Build · Think · Record", enter: "Enter", projects: "View projects" },
  bottom: [{ number: "01", label: "EXPLORE", href: "#now" }, { number: "02", label: "BUILD", href: "#projects" }, { number: "03", label: "THINK", href: "#notes" }, { number: "04", label: "LIFE", href: "#life" }],
  about: { number: "01", title: "About", lead: "Hello, I’m Joey Luo.", copy: ["I enjoy connecting ideas across different fields.", "Mathematics trained me to deconstruct problems; AI and product let me make ideas real."], facts: ["University of Waterloo\nMathematics · Statistics · Risk Management", "Currently exploring\nAI · Product · Robotics · Quantitative Thinking"] },
  now: { number: "02", title: "Now", lead: "The things currently taking up my time and curiosity.", items: [{ title: "Building this personal space", copy: "Continuing to iterate on this site." }, { title: "Exploring AI products", copy: "Thinking about AI in real workflows." }, { title: "Vision & robotics", copy: "Exploring visual localization and embodied AI." }, { title: "Quant & data", copy: "Using mathematics and statistics to understand the real world." }] },
  projects: { number: "03", title: "Projects & Experiments", lead: "A few things I have actually made.", view: "View project", items: [{ title: "AI Robot Visual Localization", tags: "Python / OpenCV / YOLO / LeRobot" }, { title: "Bond Rating Transition Model", tags: "Python / Markov Chain / Credit Risk" }, { title: "Joey Luo Personal Space", tags: "Vibe Coding / Product Design" }] },
  notes: { number: "04", title: "Notes", lead: "Thoughts worth leaving here, for now.", copy: ["In the making.", "This space will hold project reflections and new things I learn."] },
  life: { number: "05", title: "Beyond Work", lead: "There are many things I enjoy beyond screens, models, and numbers.", chess: { title: "Chess", meta: "FIDE Candidate Master (CM)", copy: "Chess taught me to enjoy the tension between long thought and short decisions." }, interests: ["Football", "Piano · ABRSM Grade 8", "Table tennis", "Basketball"], gallery: ["Chess photo", "Football photo", "Personal photo", "Travel photo"] },
  career: { number: "06", title: "Career", lead: "From finance, to data, to AI and product.", link: "View full career profile" },
  contact: { number: "07", title: "Contact", copy: "If you would like to talk about projects, AI, product, or finance, I would love to hear from you.", links: ["Email", "GitHub", "LinkedIn"] }
};

export const careerEn = {
  language: "中文 / EN", back: "Back to personal space", backToTop: "Back to top", indexLabel: "Career archive index",
  hero: { eyebrow: "CAREER ARCHIVE / 2026", school: "University of Waterloo", direction: "Mathematics · AI · Product · Quantitative Thinking", intro: "A complete record of learning, work, projects, and things I have built." },
  index: [{ label: "Education", href: "#education" }, { label: "Experience", href: "#experience" }, { label: "Projects", href: "#projects" }, { label: "Skills", href: "#skills" }, { label: "Campus", href: "#campus" }],
  education: { number: "01 / EDUCATION", title: "Education", year: "2022—2027", school: "University of Waterloo", degree: "Bachelor of Mathematics, Honours", major: "Mathematics / Risk Management", facts: ["Top 20%", "Distinction"], courses: "Coursework across statistics, actuarial science, operations research, computer science, applied mathematics, and pure mathematics.", honours: ["President’s Scholarship", "Four consecutive years of Distinction"] },
  experience: { number: "02 / EXPERIENCE", title: "Experience", mediaLabel: "Space reserved for future work records", items: [
    { company: "Shanghai Dahuan Robotics Technology Co., Ltd.", role: "AI Training & Data Assistant Intern", department: "Embodied Intelligence R&D", date: "2026.03 — 2026.04", tag: "AI / ROBOTICS", mediaLabel: "ROBOTICS", details: ["Used Codex, Python, OpenCV, and YOLO instance segmentation to process thousands of multi-angle workpiece images.", "Built a coarse-to-fine visual localization workflow and worked on SO-ARM101 calibration and LeRobot demonstration data collection."] },
    { company: "Ernst & Young Hua Ming LLP", role: "Audit Intern · Hong Kong IPO", department: "", date: "2025.07 — 2025.08", tag: "AUDIT / IPO", mediaLabel: "IPO", details: ["Cleaned and verified sales ledgers, contracts, invoices, and vouchers in Excel.", "Participated in revenue-cycle walk-through testing for a Hong Kong IPO."] },
    { company: "Guotai Haitong Securities Co., Ltd.", role: "Intern · Debt Capital Markets", department: "", date: "2025.05 — 2025.06", tag: "FIXED INCOME", mediaLabel: "BONDS", details: ["Used Wind, FICC, and Excel for bond issuance, yield, spread, and rating checks across 100+ materials.", "Built Python workflows for daily data aggregation and market review."] },
    { company: "Shenzhen Haikun Investment Management Co., Ltd.", role: "Remote Industry Research Intern", department: "Industry Research", date: "2025.02 — 2025.09", tag: "RESEARCH", mediaLabel: "RESEARCH", details: ["Wrote an AI online-education industry report using Wind data and Python analysis.", "Joined the review group for data validation, logic checks, and revision recommendations."] },
    { company: "Hong Kong Tianlong Securities Co., Ltd.", role: "Fund Manager Assistant", department: "", date: "2024.10 — 2025.01", tag: "FINANCE / PRODUCT", mediaLabel: "PRODUCT", details: ["Contributed to 0-to-1 product design for the Hong Kong Asset Management Connect app.", "Prepared a business plan and used R and Excel for financial modelling and return analysis."] }
  ] },
  projects: { number: "03 / PROJECTS & BUILDING", title: "Projects & Building", view: "View project", items: [{ title: "AI Robot Visual Localization System", subtitle: "Python / OpenCV / YOLO / LeRobot", copy: "Image segmentation → pose filtering → template matching → screw-hole localization → robotic operation.", tools: "Computer Vision · Robotics · Data" }, { title: "Bond Ratings in the Auto Industry", subtitle: "Markov-chain credit-rating model", copy: "Built rating transition matrices to study migration and the Default absorbing state.", tools: "Python · Markov Models · Credit Risk" }, { title: "Joey Luo Personal Space", subtitle: "AI-assisted Personal Website", copy: "Created a bilingual Personal / Career architecture from concept and product design through the cinematic Welcome Screen.", tools: "Product Design · Vibe Coding · AI" }] },
  skills: { number: "04 / SKILLS", title: "Skills", groups: [{ title: "Programming & Data", items: ["Python", "Pandas", "R", "SQL", "Excel / VBA", "Wind", "FICC"] }, { title: "AI & Computer Vision", items: ["Codex", "OpenCV", "YOLO", "LeRobot"] }, { title: "Quantitative", items: ["Statistics", "Risk Management", "Credit Risk", "Markov Models"] }, { title: "Product", items: ["Product Design", "User Flow", "AI-assisted Development", "Vibe Coding"] }] },
  campus: { number: "05 / CAMPUS & MORE", title: "Campus & More", club: { title: "University of Waterloo Chess Club", role: "Vice President, External Relations", details: ["Organized an inter-university match with the University of Toronto Chess Club once per term.", "Contributed to weekly events, free play, and internal tournaments."] }, notes: [{ title: "Chess", copy: "FIDE Candidate Master (CM); Asian age-group runner-up." }, { title: "Piano", copy: "ABRSM Grade 8; Music Theory Grade 5." }, { title: "Sport", copy: "Football, basketball, and table tennis." }] },
};
