import { SafeLink as Link } from "./SafeLink";

const routeMap: Record<string, string> = { "#top": "/", "#about": "/explore", "#career": "/work", "#projects": "/projects", "#life": "/life" };

export function BrandPage({ content, locale, page }: { content: any; locale: "zh" | "en"; page: "explore" | "build" | "think" | "life" }) {
  const base = locale === "zh" ? "" : "/en";
  const href = (item: any) => `${base}${routeMap[item.href]}`;
  const labels = { explore: content.about, build: content.projects, think: content.notes, life: content.life } as Record<string, any>;
  const section = labels[page];
  return <main className="brand-page"><header className="brand-header"><Link className="jl" href={base || "/"}>AJ</Link><nav>{content.nav.map((item: any) => <Link key={item.label} href={href(item)}>{item.label}</Link>)}</nav><Link className="locale" href={locale === "zh" ? "/en" : "/"}>{content.language}</Link></header><section className={`brand-section ${page}`}><div className="brand-title"><span>{section.number}</span><h1>{section.title}</h1></div>{page === "explore" && <><div className="explore-intro"><h2>{content.about.lead}</h2>{content.about.copy.map((copy: string) => <p key={copy}>{copy}</p>)}</div><div className="brand-cards">{content.about.cards.map((item: any) => <article key={item.title}><h3>{item.title}</h3><p>{item.copy}</p><div>{item.tags.map((tag: string) => <span key={tag}>{tag}</span>)}</div></article>)}</div><div className="timeline">{content.about.timeline.map((item: any) => <article key={item.year}><b>{item.year}</b><p>{item.copy}</p></article>)}</div><section className="career-preview compact"><span>{content.career.number}</span><h2>{content.career.title}</h2><p>{content.career.lead}</p><Link href={`${base}/work`}>{content.career.link} →</Link></section></>}{page === "build" && <><p className="page-lead">{content.projects.lead}</p><div className="build-list">{content.projects.items.map((item: any, index: number) => <article key={item.title}><span>{String(index + 1).padStart(2, "0")}</span><div><Link className="project-title-link" href={`${base}/projects/${item.slug}`}><h2>{item.title}</h2></Link><p className="build-subtitle">{item.subtitle}</p><p>{item.copy}</p><div className="build-meta"><span>目的：{item.copy}</span><span>技术：{item.tags}</span></div></div></article>)}</div></>}{page === "think" && <><p className="think-lead">{content.notes.lead}</p><div className="philosophy-flow">{content.notes.cards.map((item: any, index: number) => <article key={item.title}><span>0{index + 1}</span><h2>{item.title}</h2><p>{item.copy}</p></article>)}</div><div className="questions"><p>正在探索的问题</p>{content.notes.questions.map((item: string) => <span key={item}>{item}</span>)}<strong>{content.notes.philosophy}</strong></div></>}{page === "life" && <><p className="page-lead">{content.life.lead}</p><div className="life-story">{content.life.cards.map((item: any, index: number) => <article key={item.title}><i>{["♞", "◌", "♫"][index]}</i><div><h2>{item.title}</h2><p>{item.copy}</p><div>{item.tags.map((tag: string) => <span key={tag}>{tag}</span>)}</div></div></article>)}</div></>}</section><footer className="brand-footer"><span>AJ · 2026</span><nav>{content.contact.links.map((item: string) => <span key={item}>{item}</span>)}</nav></footer></main>;
}
